# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "71e9f8521247e8bb5526363e25b9960d"
name = "genarete-qrCode-app"
handle = "genarete-qrcode-app"
application_url = "https://scholarships-breaks-royal-private.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "codeconfigstore.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_product_listings,read_products,write_products"

[auth]
redirect_urls = [
  "https://scholarships-breaks-royal-private.trycloudflare.com/auth/callback",
  "https://scholarships-breaks-royal-private.trycloudflare.com/auth/shopify/callback",
  "https://scholarships-breaks-royal-private.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
